name: llr_julia
channels:
  - https://repo.prefix.dev/julia-forge
  - conda-forge
  - defaults
dependencies:
  - arpack=3.9.1
  - blas=2.132
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - curl=8.9.1
  - git=2.46.0
  - gmp=6.3.0
  - julia=1.10.4
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.8.4
  - libgomp=15.1.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libopenblas-ilp64=0.3.30
  - libopenlibm4=0.8.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libzlib=1.3.1
  - mbedtls=3.5.1
  - mpfr=4.2.1
  - ncurses=6.4
  - openblas=0.3.30
  - openblas-ilp64=0.3.30
  - openlibm=0.8.1
  - openssl=3.5.0
  - p7zip=16.02
  - pcre2=10.44
  - perl=5.40.2
  - suitesparse=7.8.3
  - tbb=2022.0.0
  - zlib=1.3.1
  - zstd=1.5.7
